version: '3'
services: 
    web:
        build: 
            context: . # where we want all the files to come from
            dockerfile: Dockerfile.dev

        ports: 
            - "3000:3000"
        volumes: 
            - /app/node_modules # do not map this folder from outside
            - .:/app
    tests:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - .:/app
        command: ["npm", "run", "test"]